services:

  redis-service:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  emrs:
    depends_on:
      redis-service:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - emrs-data:/var/lib/emrs

volumes:
  emrs-data:
